services:
  - type: web
    name: orderbook-dashboard
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRICE_STORE_CACHE_ROOT
        value: /tmp/priceStoreCache
      - key: PRICE_STORE_ZIP_ID
        sync: false
      - key: PRICE_STORE_SYMBOL_BASE_URL
        value: https://github.com/abdulrashid-valarcapital/orderbook-dashboard/releases/download/candles-5m-v1/
      - key: PRICE_STORE_SYMBOL_BASE_URL_TEMPLATE
        value: https://github.com/abdulrashid-valarcapital/orderbook-dashboard/releases/download/candles-{timeframe}m-v1/
      - key: PRICE_STORE_375_SYMBOL_BASE_URL
        value: https://github.com/abdulrashid-valarcapital/orderbook-dashboard/releases/download/candles-375m-drive-only-v1/
